[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  VITE_API_BASE_URL = "https://padelmate-backend.onrender.com"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 