services:
  - type: web
    name: padelmate-frontend
    env: static
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_BASE_URL
        value: https://padelmate-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
        status: 200 